package johnsmith.enchantingoverhauled.api.enchantment;

import net.minecraft.util.ByIdMap;

import java.util.Arrays;
import java.util.function.IntFunction;

/**
 * Defines the origin or source of an enchantment displayed in the custom Enchanting Table GUI.
 * <p>
 * This enumeration is used internally by the {@link johnsmith.enchantingoverhauled.mixin.menu.EnchantmentMenuMixin}
 * to distinguish between the three potential actions when enchanting an item:
 * <ul>
 * <li>**TARGET**: Upgrading an existing enchantment directly on the item being enchanted.</li>
 * <li>**SOURCE**: Transferring an enchantment from the secondary item/book (source slot).</li>
 * <li>**TABLE**: Applying a new, random enchantment generated by the enchanting table.</li>
 * </ul>
 */
public enum EnchantmentSource {
    /**
     * Represents a null or uninitialized source (ID: -1).
     */
    NONE(-1),
    /**
     * The enchantment originated from the **Target** item itself (for upgrading existing enchantments). (ID: 0)
     */
    TARGET(0),
    /**
     * The enchantment originated from the **Source** item (e.g., a Tome) in the dedicated source slot (for transferring enchantments). (ID: 1)
     */
    SOURCE(1),
    /**
     * The enchantment is a **new** one generated by the enchantment table/altar. (ID: 2)
     */
    TABLE(2);

    private final int id;

    /**
     * Constructs an {@code EnchantmentSource} with a unique integer identifier.
     *
     * @param id The integer ID used for synchronization between server and client.
     */
    EnchantmentSource(int id) {
        this.id = id;
    }

    /**
     * Retrieves the integer ID of this source type.
     *
     * @return The unique integer ID.
     */
    public int getId() {
        return id;
    }

    /**
     * An efficient lookup function built using {@link ByIdMap} for all valid, non-negative source IDs.
     * {@code NONE(-1)} is explicitly excluded from this map construction.
     */
    private static final IntFunction<EnchantmentSource> BY_ID = ByIdMap.continuous(
            EnchantmentSource::getId,
            Arrays.stream(values()).filter(v -> v.id >= 0).toArray(EnchantmentSource[]::new),
            ByIdMap.OutOfBoundsStrategy.WRAP
    );

    /**
     * Retrieves the {@code EnchantmentSource} enum constant matching the given integer ID.
     *
     * @param id The integer ID to look up.
     * @return The corresponding {@code EnchantmentSource} constant, or {@code NONE} if the ID is -1.
     */
    public static EnchantmentSource byId(int id) {
        if (id == -1) return NONE;
        return BY_ID.apply(id);
    }
}